#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: gnome-icon-theme-gnamon
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2012 Luis Alejandro Martínez Faneyth <luis@huntingbears.com.ve>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
	printf "\033[1,31m${1}\033[0m\n"
}

ADVERTENCIA() {
	printf "\033[1,33m${1}\033[0m\n"
}

EXITO() {
	printf "\033[1,32m${1}\033[0m\n"
}

case ${1} in

	triggered)
		if [ -x /usr/bin/gtk-update-icon-cache-3.0 ]; then
			if ! gtk-update-icon-cache-3.0 --force --quiet /usr/share/icons/Gnamon; then
				ERROR "¡El caché de iconos no pudo generarse!"
			fi
		fi
		exit 0
	;;

	configure|'')

		ADVERTENCIA "Estableciendo cursores de Canaima por defecto ..."
		update-alternatives --force --install /usr/share/icons/default/index.theme x-cursor-theme /usr/share/icons/GnamonCur/cursor.theme 90

		ADVERTENCIA "Estableciendo iconos de Canaima por defecto ..."
		SIZES=$( ls /usr/share/icons/Gnamon/places | sed "s|scalable||g" )
		COMMAND="update-alternatives --force --install /usr/share/icons/Gnamon/places/scalable/start-here.svg start-here.svg /usr/share/icons/Gnamon/places/scalable/canaima-logo.svg 90"

		for S in $SIZES; do
			COMMAND="$COMMAND --slave /usr/share/icons/Gnamon/places/${S}/start-here.png start-here-${S}.png /usr/share/icons/Gnamon/places/${S}/canaima-logo.png"
		done

		eval "${COMMAND}"

		if [ -x /usr/bin/gtk-update-icon-cache-3.0 ]; then
			if ! gtk-update-icon-cache-3.0 --force --quiet /usr/share/icons/Gnamon; then
				ERROR "¡El caché de iconos no pudo generarse!"
			fi
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		ERROR "postinst no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
