#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: gnome-icon-theme-gnamon
# ARCHIVO: postrm
# DESCRIPCIÓN: Revierte los cambios hechos por el paquete en los scripts del
#              mantenedor, de forma tal de asegurarse que el sistema quede
#              como estaba antes de su instalación.
# COPYRIGHT:
#  (C) 2012 Luis Alejandro Martínez Faneyth <luis@huntingbears.com.ve>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
	printf "\033[1,31m${1}\033[0m\n"
}

ADVERTENCIA() {
	printf "\033[1,33m${1}\033[0m\n"
}

EXITO() {
	printf "\033[1,32m${1}\033[0m\n"
}

case ${1} in

	purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		if [ -x /usr/bin/gtk-update-icon-cache-3.0 ]; then
			if ! gtk-update-icon-cache-3.0 --force --quiet /usr/share/icons/Gnamon; then
				ERROR "¡El caché de iconos no pudo generarse!"
			fi
		fi
	;;

	*)
		ERROR "postrm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
