#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: gnome-icon-theme-gnamon
# ARCHIVO: prerm
# DESCRIPCIÓN: Prepara el sistema para que el paquete sea removido.
# COPYRIGHT:
#  (C) 2012 Luis Alejandro Martínez Faneyth <luis@huntingbears.com.ve>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
	printf "\033[1,31m${1}\033[0m\n"
}

ADVERTENCIA() {
	printf "\033[1,33m${1}\033[0m\n"
}

EXITO() {
	printf "\033[1,32m${1}\033[0m\n"
}

case ${1} in

	remove|upgrade|deconfigure)

		ADVERTENCIA "Removiendo cursores de Canaima ..."
		update-alternatives --remove x-cursor-theme /usr/share/icons/GnamonCur/cursor.theme

		ADVERTENCIA "Removiendo iconos de Canaima ..."
		update-alternatives --remove start-here.svg /usr/share/icons/Gnamon/places/scalable/canaima-logo.svg

	;;

	failed-upgrade)
	;;

	*)

		ERROR "prerm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
